export const FETCH_TOP_VOLUME_24 = 'FETCH_TOP_VOLUME_24';
export const FETCH_TOP_VOLUME_24_SUCCEED = 'FETCH_TOP_VOLUME_24_SUCCEED';

export const FETCH_COIN_HISTORY_DAY = 'FETCH_COIN_HISTORY_DAY';
export const FETCH_COIN_HISTORY_DAY_SUCCEED = 'FETCH_COIN_HISTORY_DAY_SUCCEED';

export const FETCH_COIN_FULL_DATA = 'FETCH_COIN_FULL_DATA';
export const FETCH_COIN_FULL_DATA_SUCCEED = 'FETCH_COIN_FULL_DATA_SUCCEED';

export const FETCH_DETAILS = 'FETCH_DETAILS';
export const FETCH_DETAILS_SUCCEED = 'FETCH_DETAILS_SUCCEED';

export const FETCH_FAILED = 'FETCH_FAILED';
export const CLEAR_ERROR = 'CLEAR_ERROR';

export const SAVE_SCROLL_POSITION = 'SAVE_SCROLL_POSITION';
